version: 2
project_name: balancepush-link-regenerator
before:
  hooks:
    - go mod tidy
    - go mod download
builds:
  - binary: bprenew
    ldflags: -s -w -X main.Version={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - freebsd
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: freebsd
        goarch: arm64
      - goos: darwin
        goarch: amd64
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-snapshot"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
gomod:
  proxy: false
